### DISCUSSION TITLE
2024/7 Breaking Change

### DISCUSSION THREAD

**Discussion by julianlawson** [bkbilly/lnxlink#116] [Q&A]
The documentation for 2024.7 says "Breaking change: Bash configuration new option allow_any_command for allowing running arbitrary commands" -- but I can't find anything in the documentation that explains what will be broken, or how allow_any_command should be used. (I am guessing this refers to a comment made about whitelisting commands vs allowing any bash command to run). Has anyone got an example of how this works?

**Comment by bkbilly** [comment]
The `allow_any_command` option gets the values `true` or the default `false`.
This used to allow any command to run, so with the new version, it ignores any command that is sent if it is not in the list of commands.
To revert to the previous way it was working, it should be changed to `true`.

For example in this configuration, it will only run the command `docker system prune -af`:
```yaml
...
settings:
  bash:
    allow_any_command: false
    expose:
    - name: Prune Docker
      type: button
      command: docker system prune -af
```
If I change `allow_any_command` to `true`, it will run any command like `rm myfile.txt`
```yaml
...
settings:
  bash:
    allow_any_command: true
    expose:
    - name: Prune Docker
      type: button
      command: docker system prune -af
```
Hope this clears things up.
