### DISCUSSION TITLE
Sync PC screens with presence/lights

### DISCUSSION THREAD

**Discussion by D3SOX** [bkbilly/lnxlink#176] [Show and tell]
I'm using an Aqara FP2 Human Presence Sensor and automated my pc screens with the desk presence. It also turns them off when the lights are turned off and the PC is not idling.

This could fit on the [docs automations page](https://bkbilly.gitbook.io/lnxlink/automations) in a modified form

As the LNXLink `idle` module does not work for KDE Wayland I currently use [kiot](https://github.com/davidedmundson/kiot) for detecting inactivity for the lights trigger
Same for the screens module, that's why I'm using my module right now. [`https://github.com/D3SOX/lnxlink-modules/blob/master/kde_screens_onoff.py`](https://github.com/D3SOX/lnxlink-modules/blob/master/kde_screens_onoff.py)

Also, please tell me if there is a better way to detect if LNXLink is available

```yaml
alias: PC screens auto on/off
description: >-
  Automatically switch PC screens with desk presence and turn off when room
  lights are turned off and inactive (Currently requires kiot)
triggers:
  - trigger: state
    entity_id:
      - light.lights_my_room
    to: "off"
    from: "on"
    id: lights_off
    for:
      hours: 0
      minutes: 0
      seconds: 1
  - trigger: state
    entity_id:
      - binary_sensor.presence_desk
    id: clear
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 35
  - trigger: state
    entity_id:
      - binary_sensor.presence_desk
    to: "on"
    from: "off"
    id: detected
conditions:
  - condition: template
    value_template: >-
      {{ states('switch.nico_pc_screens_onoff_kde') != 'unknown' and
      states('switch.nico_pc_screens_onoff_kde') != 'unavailable' }}
    alias: If LNXLink is available
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - lights_off
        sequence:
          - alias: If active wait for inactive, then turn screens off
            if:
              - condition: state
                entity_id: binary_sensor.nico_pc_active
                state: "on"
                alias: If nico-pc is active
            then:
              - alias: Wait for 1s inactivity (timeout 30s)
                wait_for_trigger:
                  - trigger: state
                    entity_id:
                      - binary_sensor.nico_pc_active
                    to: "off"
                    for:
                      hours: 0
                      minutes: 0
                      seconds: 1
                continue_on_timeout: false
                timeout:
                  hours: 0
                  minutes: 0
                  seconds: 30
                  milliseconds: 0
              - action: switch.turn_off
                target:
                  entity_id: switch.nico_pc_screens_onoff_kde
            else:
              - action: switch.turn_off
                target:
                  entity_id: switch.nico_pc_screens_onoff_kde
      - conditions:
          - condition: trigger
            id:
              - clear
        sequence:
          - action: switch.turn_off
            target:
              entity_id: switch.nico_pc_screens_onoff_kde
      - conditions:
          - condition: trigger
            id:
              - detected
        sequence:
          - action: switch.turn_on
            target:
              entity_id: switch.nico_pc_screens_onoff_kde
mode: restart

```
