### DISCUSSION TITLE
Supported Modules for Docker Install Method

### DISCUSSION THREAD

**Discussion by holocronweaver** [bkbilly/lnxlink#178] [Q&A] [answered]
I noticed the Docker install method doc mentions that some modules are not supported. Which modules are supported?

It seems modules that rely on systemd, like `suspend`, do not work (though it seems it is possible in principle to [allow containers to interact with the host systemd](https://medium.com/opsops/accessing-host-system-systemd-from-containers-systemctl-492a1a385102)). Are there any other modules known not to work?

**Comment by bkbilly** [comment, marked as answer]
I looked into the `suspend`, and it seems that by installing the systemd on the docker image, it should work the suspend. Unfortunately I couldn't make it work for systemd module.

As for the other unsupported modules, you can find the ones that are not supported here:
https://github.com/bkbilly/lnxlink/blob/master/Dockerfile

Here is the current list of modules that are excluded from running in the docker image:
- audio_select
- bluetooth
- boot_select
- keep_alive
- power_profile
- screen_onoff
- screenshot
- speech_recognition
- suspend
- systemd
- webcam
- wifi

In addition to these, the media module doesn't support system volume control, so you will see that the volume is always at 100%.

**Reply by holocronweaver** [reply]
Thanks! I saw you updated the Docker container to install systemd, so I tried it out. However suspend failed due to requiring interactive password entry:
```
lnxlink  | INFO:lnxlink:Message received suspend/suspend: b'PRESS'
lnxlink  | Failed to execute /usr/bin/pkttyagent: No such file or directory
lnxlink  | ERROR:lnxlink:Error with command: systemctl suspend (Call to Suspend failed: Interactive authentication required.)
```
Here is my Docker Compose:
```
services:
  lnxlink:
    # image: bkbillybk/lnxlink:2025.5.0
    image: holocronweaver/lnxlink:systemd
    container_name: lnxlink
    restart: unless-stopped
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    user: "1000:1000" # UID:GID
    ports:
      - 8112:8112
    volumes:
      - /data/lnxlink/:/opt/lnxlink/config/
      - /var/run/reboot-required:/var/run/reboot-required:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/user/1000/bus:/var/run/user/1000/bus
      - /var/run/dbus/:/var/run/dbus/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /proc/:/proc/
      - /dev/:/dev/
      - /run:/run
    environment:
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
      - DISPLAY=$DISPLAY
      - SYSTEMCTL_FORCE_BUS=1
```
I tried adding an entry to sudoers, but it made no difference:
```
myuser   ALL=(ALL) NOPASSWD: /usr/bin/systemctl suspend
```
When I run `systemctl suspend` in a terminal, without `sudo`, I am not prompted for a password, and suspend works as expected when running lnxlink. lnxlink installed via regular non-root install is able to suspend without issue.

Any idea how to work around this issue? 

Edit: forgot to mention that I tried running the container with `user: "0:0"` and  it did not prompt for a password or give an error, but the system also did not suspend.
