### ISSUE TITLE
Increasing/decreasing volume by a predefined step

### ISSUE THREAD

**Issue by Dinth** [bkbilly/lnxlink#101]
### Describe the solution you'd like

Hi. Is there a way to increase/decrease system volume by a predefined set? Im looking to integrate my Symfonisk knob remote with my computer using lnxlink

**Comment by bkbilly** [comment]
You can change the volume with the `media_player.volume_down`, but this changes it by 5%.
You can use templates to set any value you want:
```yaml
service: media_player.volume_set
data:
  volume_level: '{{ state_attr("media_player.desktop_linux", "volume_level") - 0.01 }}'
target:
  entity_id: media_player.desktop_linux
```
