### ISSUE TITLE
Request for arbitrary bash sensors

### ISSUE THREAD

**Issue by julianlawson** [bkbilly/lnxlink#109]
### Describe the solution you'd like

Hi, you've probably covered the vast majority of sensors we need, but it would be great to have the option to have run bash scripts and take the output as the value of a sensor. 

I've worked around this to create an MQTT sensor to figure out if the screen is locked or not with a script that I run periodically (sorry I can't figure out how to properly escape the backquotes): 

```
mosquitto_pub -h homeassistant.local -u SECRET -P SECRET -t "lnxlink/juba-mint/sensors/screenlock" -m `cinnamon-screensaver-command -q | head -n 1 | sed 's/The screensaver is //'`

```

It would be great if I could do this directly maybe with something like this:
```
  bash:
    expose: 
    - sensor: Screen Lock
      command: cinnamon-screensaver-command -q | head -n 1 | sed 's/The screensaver is //'
      frequency: 1 # run every second
```

**Comment by bkbilly** [comment]
This is already supported by setting it up under the settings on the configuration file of LNXlink:
https://bkbilly.gitbook.io/lnxlink/settings#bash

```yaml
settings:
  bash:
    expose:
    - name: Prune Docker
      command: docker system prune -af
      icon: mdi:script-text
```

**Comment by julianlawson** [comment]
Hi, I don't think I explained myself very well. As far as I understand it, the current "bash" module is exposed in Home Assistant as a _button_, and executes bash code but does not return any information back to Home Assistant.

I'm looking for the ability to create a _sensor_ whose value is populated by the stdout of executing a bash command. I've pasted a screenshot of the command I use, if that helps

![image](https://github.com/bkbilly/lnxlink/assets/66686852/8ecdd0a0-66c0-4b82-841b-8e11eab9842a)

**Comment by bkbilly** [comment]
Oh sorry, my bad...
I didn't read very well what you wrote.

I'll keep that in mind for a future update.

**Comment by bkbilly** [comment]
I've added this functionality of exposing a bash command as a sensor.
It will be available on the next release that I am going to publish in a few days/hours.

The supported entities are button and sensor and It will work like this:
```yaml
settings:
  bash:
    expose:
    - name: Prune Docker
      type: button
      command: docker system prune -af
    expose:
    - name: Load 1minute
      type: sensor
      command: cat /proc/loadavg | awk '{print $1}'
      unit: load
```

If the type is not provided, it defaults to button so it can be compatible with previous configurations.
