### ISSUE TITLE
Documentation: Error in Bash `expose` command format

### ISSUE THREAD

**Issue by jeremysherriff** [bkbilly/lnxlink#113]
### What type of installation are you running?

Server

### Which Linux OS are you using?

Ubuntu 22.04

### Which version of LNXLink has the issue?

2024.6.1

### Describe the problem

Documentation is incorrect at https://bkbilly.gitbook.io/lnxlink/settings#bash

Currently reads:
```
settings:
  bash:
    expose:
    - name: Prune Docker
      type: button
      command: docker system prune -af
      icon: mdi:script-text
    expose:
    - name: Load 1minute
      type: sensor
      command: cat /proc/loadavg | awk '{print $1}'
      unit: load
```

I found that this only loads the last sensor/button.  The additional `expose` key causes the first definition to be ignored/replaced.

The correct format is:
```
settings:
  bash:
    expose:
    - name: Prune Docker
      type: button
      command: docker system prune -af
      icon: mdi:script-text
    - name: Load 1minute
      type: sensor
      command: cat /proc/loadavg | awk '{print $1}'
      unit: load
```
