### ISSUE TITLE
Bash command missing.

### ISSUE THREAD

**Issue by hagier** [bkbilly/lnxlink#127]
### What type of installation are you running?

Desktop

### Which Linux OS are you using?

Ubuntu 23.10

### Which version of LNXLink has the issue?

2024.9.0

### Describe the problem

I was using Bash command module and not it's not available through MQTT:

![image](https://github.com/user-attachments/assets/701ad3de-8cdf-47b2-9d78-cc3f3a805bcf)

I still have it in config:

```yaml
update_interval: 30
modules:
- bash
- battery
- cpu
- memory
- network
- required_restart
- restart
- screenshot
- shutdown
- suspend
- sys_updates
- update
custom_modules: null
```
