### ISSUE TITLE
Not Sending MQTT Messages After Install

### ISSUE THREAD

**Issue by Daniel-dev22** [bkbilly/lnxlink#13]
I installed this on a nuc running ubuntu server.
Here's my configuration. I assume similar to iotlink this is meant to send messages constantly, however I restarted the service a few times and nothing happened.

Initially I thought it could be because I have another server that uses iotlink and the same prefix but changing that and restarting didn't help either.

```
mqtt:
  prefix: iotlink/workgroupp
  clientId: ubuntu-nuc
  statsPrefix: ubuntu-monitor/stats
  server: 192.168.4.32
  port: '1883'
  auth:
    user: user
    pass: pw
  discovery:
    enabled: true
  lwt:
    enabled: true
    qos: 1
    retain: true
    connectMsg: 'ON'
    disconnectMsg: 'OFF'
control:
- shutdown
- restart
- send-keys
- run
- notify
- media
monitoring:
- cpu
- memory
```

**Comment by bkbilly** [comment]
Try running it manually to check the errors like so:
``` bash
systemctl --user stop lnxlink.service
cd /opt/lnxlink/
python3 run.py
```

**Comment by bkbilly** [comment]
Oh. I see the problem.
Make the port as int and the server as string like so:

```yaml
mqtt:
  prefix: lnxlink/workgroupp
  clientId: ubuntu-nuc
  statsPrefix: ubuntu-monitor/stats
  server: '192.168.4.148'
  port: 1883
  auth:
    user: user
    pass: pw
  discovery:
    enabled: true
  lwt:
    enabled: true
    qos: 1
    retain: true
    connectMsg: 'ON'
    disconnectMsg: 'OFF'
control:
- shutdown
- restarts
- run
monitoring:
- cpu
- memory
- network
- media
```
