### ISSUE TITLE
Bash Commands Not Importing into Home Assistant

### ISSUE THREAD

**Issue by MessOfCrumbs** [bkbilly/lnxlink#139]
### What type of installation are you running?

Server

### Which Linux OS are you using?

Rocky Linux 9.5 (Blue Onyx)

### Which version of LNXLink has the issue?

2024.11.0

### Describe the problem

When setting up LNXLink on a test box  I can't get the bash commands to appear in Home Assistant after adding them to lnxlink.yaml and restarting the service. From reading the documentation it feels like my configuration should be correct? I copied in the demo config for the bash section and that doesn't ever show in home assistant either. Everything else shows as expected though - just not bash commands. Any advice? Bug maybe - I saw a previous bug report for this but it was closed from inactivity. 

![image](https://github.com/user-attachments/assets/a91e2b23-5c18-4be5-9f7e-1c4267a6be92)

Appreciate the work, the whole homelab will be getting this project installed!

### Configuration

```yaml
mqtt:
  prefix: lnxlink
  clientId: NAME-WAS-HERE
  server: IP-WAS-HERE
  port: 1883
  auth:
    user: USERNAME-HERE
    pass: PASSWORD-HERE
    tls: false
    keyfile: ''
    certfile: ''
    ca_certs: ''
  discovery:
    enabled: false
  lwt:
    enabled: true
    qos: 1
    retain: false
update_interval: 5
update_on_change: false
hass_url: null
hass_api: null
modules:
- active_window
- bash
- cpu
- disk_io
- disk_usage
- interfaces
- memory
- network
- power_profile
- required_restart
- restart
- shutdown
- sys_updates
- temperature
- update
custom_modules: null
exclude: null
settings:
  systemd: null
  gpio:
    inputs: null
    outputs: null
  hotkeys: null
  disk_usage:
    include_disks: []
    exclude_disks: []
  statistics: https://analyzer.bkbilly.workers.dev
  bash:
    allow_any_command: false
    expose:
    - name: Prune Docker
      type: button
      command: docker system prune -af
      icon: mdi:script-text
      entity_category: config
    - name: Load 1minute
      type: sensor
      command: cat /proc/loadavg | awk '{print $1}'
      unit: load
      entity_category: diagnostic
    - name: WiFi Exists
      type: binary_sensor
      command: ip a | grep wlan0
    - name: Microphone Mute
      type: switch
      command: amixer get Capture | grep "\[off\]"
      command_on: amixer set Capture nocap
      command_off: amixer set Capture cap
  mounts:
    autocheck: false
    directories: []
  ir_remote:
    receiver: null
    transmitter: null
    buttons: []
  restful:
    port: 8112
```

### Logs

```bash
2024-12-07 14:31:22,426 [9882:MainThread.__main__.__init__.46] [INFO]  LNXlink 2024.11.0, Python 3.9.19
2024-12-07 14:31:22,441 [9882:MainThread.helpers.import_install_package.73] [ERROR]  Can't import package dasbus: No module named 'gi'
2024-12-07 14:31:22,441 [9882:MainThread.system_monitor.__init__.20] [ERROR]  Can't use DBus for system monitor
2024-12-07 14:31:22,547 [9882:MainThread.__main__.start.88] [INFO]  Loaded addons: active_window, bash, cpu, disk_io, disk_usage, interfaces, memory, network, power_profile, required_restar>
2024-12-07 14:31:22,549 [9882:paho-mqtt-client-.__main__.on_connect.246] [INFO]  MQTT connection: Success
```
