### ISSUE TITLE
Could not load DBusIdleMonitor and XprintidleIdleMonitor

### ISSUE THREAD

**Issue by ErikSteiner** [bkbilly/lnxlink#140]
### What type of installation are you running?

Desktop

### Which Linux OS are you using?

PostmarketOS v24.06 (Mate 7)

### Which version of LNXLink has the issue?

2024.11.0

### Describe the problem

Activating the `idle` module results in printed errors in terminal:
`Could not load DBusIdleMonitor`

However, the idle time is send to Home Assistant. Unfortunately, the idle time will stop be transmitted after a while, because the X11 server complains of too many registered clients:
`Maximum number of clients reached`

If I use this little example here from `dbus-idle`, everything is reported correctly, and no issue with `DBusIdleMonitor` is reported:
```
from dbus_idle import IdleMonitor
import sched, time

def do_something(scheduler): 
    # schedule the next call first
    scheduler.enter(15, 1, do_something, (scheduler,))
    print(IdleMonitor().get_dbus_idle())

my_scheduler = sched.scheduler(time.time, time.sleep)
my_scheduler.enter(15, 1, do_something, (my_scheduler,))
my_scheduler.run()
```
It prints the idle time every 15 seconds. If you move the mouse between one of those printed lines, the idle time is resetted.

### Additional context

Install procedure:
```
sudo apk add gcc python3-dev musl-dev linux-headers pipx py3-gobject3 py3-dasbus
pipx ensurepath
pipx install lnxlink

# Navigate to /home/YOURUSER/.local/share/pipx/venvs/lnxlink and open `pyvenv.cfg`
# set the value from false to true, to import also system packages, that possibly were installed after venv creation:
include-system-site-packages = true

# You can test it, if you now try to install dbus-idle, what failed before the modification:
pipx inject lnxlink dbus-idle

lnxlink -sc config.yaml
```

### Configuration

```yaml
mqtt:
  prefix: lnxlink
  clientId: tablet-eg
  server: 192.168.1.10
  port: 1883
  auth:
    user: theuser
    pass: thepass
    tls: false
    keyfile: ''
    certfile: ''
    ca_certs: ''
  discovery:
    enabled: true
  lwt:
    enabled: true
    qos: 1
    retain: false
update_interval: 5
update_on_change: false
hass_url: null
hass_api: null
modules: null
custom_modules: null
exclude:
- audio_select
- bash
- battery
- boot_select
- brightness
- fullscreen
- gpio
- gpu
- inference_time
- ir_remote
- keep_alive
- keyboard_hotkeys
- media
- mouse
- network
- notify
- power_profile
- restful
- screen_onoff
- screenshot
- send_keys
- speech_recognition
- systemd
- webcam
- xdg_open
- statistics
- docker
- bluetooth
- sys_updates
- wifi
- steam
- camera_used
- disk_io
- disk_usage
- gamepad
- microphone_used
- mounts
- restart
- shutdown
- speaker_used
- suspend
settings:
  systemd: null
  gpio:
    inputs: null
    outputs: null
  hotkeys: null
  disk_usage:
    include_disks: []
    exclude_disks: []
  statistics: https://analyzer.bkbilly.workers.dev
  bash:
    allow_any_command: false
    expose: null
  mounts:
    autocheck: false
    directories: []
  ir_remote:
    receiver: null
    transmitter: null
    buttons: []
  restful:
    port: 8112
```

### Logs

```bash
Neither `systemd` nor `journalctl` is available. Copied from terminal:

$ lnxlink -c config.yaml
INFO:lnxlink:SystemD service not found or it's not running...
 Install as a user service? (True/False) [True]: 
/bin/sh: systemctl: not found
/bin/sh: systemctl: not found
INFO:lnxlink:LNXlink 2024.11.0, Python 3.12.8
INFO:lnxlink:Loaded addons: active_window, cpu, display_env, idle, interfaces, memory, required_restart, temperature, update
INFO:lnxlink:MQTT connection: Success
WARNING:dbus_idle:Could not load DBusIdleMonitor
WARNING:dbus_idle:Could not load XprintidleIdleMonitor
WARNING:dbus_idle:Could not load DBusIdleMonitor
WARNING:dbus_idle:Could not load XprintidleIdleMonitor
WARNING:dbus_idle:Could not load DBusIdleMonitor
WARNING:dbus_idle:Could not load XprintidleIdleMonitor
^CINFO:lnxlink:stopped gracefully
INFO:lnxlink:Power Down detected.
INFO:lnxlink:Disconnected from MQTT.
```
