### ISSUE TITLE
When using with Docker there is a failure message about git

### ISSUE THREAD

**Issue by giggio** [bkbilly/lnxlink#157]
### What type of installation are you running?

Server

### Which Linux OS are you using?

Debian 12

### Which version of LNXLink has the issue?

2025.2.0

### Describe the problem

I'm getting this error when the container starts:

```console
Error with command: git -C /opt/lnxlink rev-parse --short HEAD (/bin/sh: 1: git: not found)
```

### Configuration

```yaml
mqtt:
  prefix: lnxlink
  clientId: foo
  server: bar
  port: baz
  auth:
    user: xx
    pass: yy
    tls: true
    keyfile: ''
    certfile: ''
    ca_certs: ''
  discovery:
    enabled: true
  lwt:
    enabled: true
    qos: 1
    retain: false
update_interval: 15
update_on_change: true
hass_url: null
hass_api: null
modules:
- bash
- cpu
- disk_usage
- inference_time
- memory
- network
- required_restart
- restart
- restful
- shutdown
- sys_updates
- systemd
- temperature
- update
custom_modules: null
exclude:
- battery
- boot_select
- brightness
- fullscreen
- gamepad
- gpio
- gpu
- ir_remote
- keep_alive
- keyboard_hotkeys
- mouse
- notify
- power_profile
- screenshot
- send_keys
- speech_recognition
- statistics
- webcam
- xdg_open
settings:
  systemd:
  - docker.service
  disk_usage:
    include_disks:
      - /dev/nvme0n1
    exclude_disks: []
  statistics: null
  bash:
    allow_any_command: false
    expose: null
  mounts:
    autocheck: false
    directories: []
  restful:
    port: 8112
```

### Logs

```log
lnxlink  | Error with command: git -C /opt/lnxlink rev-parse --short HEAD (/bin/sh: 1: git: not found)
lnxlink  | INFO:lnxlink:By not setting up the SystemD, LNXlink won't be able to start on boot...
lnxlink  | INFO:lnxlink:LNXlink 2025.2.0+edit, Python 3.12.9
lnxlink  | INFO:waitress:Serving on http://0.0.0.0:8112
lnxlink  | INFO:lnxlink:Loaded addons: bash, cpu, disk_usage, inference_time, memory, network, required_restart, restart, restful, shutdown, sys_updates, systemd, temperature, update
lnxlink  | INFO:lnxlink:Using MQTT ca_certs: None
lnxlink  | INFO:lnxlink:Using MQTT certfile: None
lnxlink  | INFO:lnxlink:Using MQTT keyfile: None
lnxlink  | INFO:lnxlink:MQTT connection: Success
```
