### ISSUE TITLE
Query night mode

### ISSUE THREAD

**Issue by qgjdev** [bkbilly/lnxlink#164]
### Describe the solution you'd like

Hey,
I was wondering if it was possible to query the night mode state of the OS.

For example, it would be great to have my RGB LEDs automatically turn on through home assistant when my PC switches to night mode.

**Comment by bkbilly** [comment]
You can use the bash script to get the night mode using this:
```yaml
  bash:
    expose:
    - name: Night Mode
      type: binary_sensor
      command: gdbus call --session --dest org.gnome.SettingsDaemon.Color --object-path /org/gnome/SettingsDaemon/Color --method org.freedesktop.DBus.Properties.Get "org.gnome.SettingsDaemon.Color" "NightLightActive" | grep -oE 'true|false'
```
