### ISSUE TITLE
Docker-compose example reboot-required volume does not work

### ISSUE THREAD

**Issue by chrisbennight** [bkbilly/lnxlink#182]
### What type of installation are you running?

Server

### Which Linux OS are you using?

24.04

### Which version of LNXLink has the issue?

2025.6.0

### The problem

The example docker compose here: https://bkbilly.gitbook.io/lnxlink/setup shows making the host reboot-required canary file available in the container like : 
```- /var/run/reboot-required:/var/run/reboot-required:ro```

When the file does not exist on the host running that command will result in a directory at /var/run/reboot-required being created.

I tried using the long form syntax to disable implicit directory creation:

```
- type: bind
        source: /var/run/reboot-required
        target: /var/run/reboot-required
        read_only: true
        bind:
          create_host_path: false
```

but docker will not create this bind mount if the source doesn't exist.

At this point I'm not sure how to make the reboot-required file available in docker (or if it's possible)
If it is indeed not possible the line mounting it as a volume in the docker-compose.yml from the docs should probably be removed.
