### ISSUE TITLE
Error with Bluetooth Module

### ISSUE THREAD

**Issue by D3SOX** [bkbilly/lnxlink#187]
### What type of installation are you running?

Desktop

### Which Linux OS are you using?

Arch Linux

### Which version of LNXLink has the issue?

2025.6.0

### Describe the problem

Bluetooth module doesn't start up

### Configuration

```yaml
mqtt:
  prefix: lnxlink
  discovery:
    enabled: true
  lwt:
    enabled: true
    qos: 1
    retain: false
update_interval: 5
update_on_change: false
hass_url: null
hass_api: null
modules:
- battery
- bluetooth
- camera_used
- media
- logging_level
- microphone_used
- notify
- restart
- shutdown
- speaker_used
- suspend
- update
custom_modules:
- https://raw.githubusercontent.com/D3SOX/lnxlink-modules/master/kde_screens_onoff.py
exclude:
- audio_select
- bash
- battery
- boot_select
- brightness
- fullscreen
- gpio
- gpu
- idle
- inference_time
- ir_remote
- keep_alive
- keyboard_hotkeys
- media
- mouse
- network
- notify
- power_profile
- restful
- screen_onoff
- screenshot
- send_keys
- speech_recognition
- systemd
- webcam
- xdg_open
settings:
```

### Logs

```bash
Jun 18 13:28:18 nico-pc lnxlink[2680009]: ERROR:lnxlink:Error with command: bluetoothctl info Media ()
Jun 18 13:28:18 nico-pc lnxlink[2680009]: ERROR:lnxlink:Error with addon bluetooth, please remove it from your config: not enough values to unpack (expected 3, got 2)
```
