### ISSUE TITLE
Can't load addon: nvidia_gpu

### ISSUE THREAD

**Issue by r14n** [bkbilly/lnxlink#50]
**Describe the problem**
When I run lnxlink -c config.yaml I get the error Can't load addon: nvidia_gpu

```
LNXlink 2023.4.0 started: 3.10.6
Successfully loaded addon: xdg_open
Successfully loaded addon: bash
Successfully loaded addon: cpu
Successfully loaded addon: restart
Successfully loaded addon: battery
Successfully loaded addon: network_upload
Successfully loaded addon: memory
Successfully loaded addon: suspend
Successfully loaded addon: update
Successfully loaded addon: screen_onoff
Successfully loaded addon: idle
Successfully loaded addon: disk_usage
Successfully loaded addon: nvidia_gpu
Successfully loaded addon: sys_updates
Successfully loaded addon: camera_used
Successfully loaded addon: media
Successfully loaded addon: keep_alive
Successfully loaded addon: send_keys
Successfully loaded addon: notify
Successfully loaded addon: shutdown
Successfully loaded addon: required_restart
Successfully loaded addon: microphone_used
Successfully loaded addon: webcam
Successfully loaded addon: network_download
Connected to MQTT with code 0
Can't load addon: nvidia_gpu
Traceback (most recent call last):
  File "/home/r14n/.local/lib/python3.10/site-packages/lnxlink/__main__.py", line 62, in monitor_run
    pub_data = addon.getInfo()
  File "/home/r14n/.local/lib/python3.10/site-packages/lnxlink/modules/nvidia_gpu.py", line 12, in getInfo
    stdout = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nvidia-smi'
Can't load addon: nvidia_gpu
Traceback (most recent call last):
  File "/home/r14n/.local/lib/python3.10/site-packages/lnxlink/__main__.py", line 62, in monitor_run
    pub_data = addon.getInfo()
  File "/home/r14n/.local/lib/python3.10/site-packages/lnxlink/modules/nvidia_gpu.py", line 12, in getInfo
    stdout = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nvidia-smi'

```

**Desktop (please complete the following information):**
 - OS: Pop_OS
 - Version Pop!_OS 22.04 LTS

**Additional context**
I don't have Nvidia, how to disable looking for it?  I have  intel integrated Mesa Intel® Graphics (ADL GT2)

**Configuration**
Provide the configuration file, remove any sensitive info that might exist:
```yaml
mqtt:
  prefix: lnxlink
  clientId: DESKTOP-Linux
  statsPrefix: monitor/stats
  server: 192.168.100.3
  port: 1883
  auth:
    user: XXXXXXXXXXXXXX
    pass: XXXXXXXXXXXXXX
  discovery:
    enabled: true
  lwt:
    enabled: true
    qos: 1
    retain: true
    connectMsg: 'ON'
    disconnectMsg: 'OFF'
update_interval: 5
modules: null
```
