### ISSUE TITLE
Is there a way to know that my laptop is turned off?

### ISSUE THREAD

**Issue by bmcclure** [bkbilly/lnxlink#55]
I have lnxlink on my dev laptop. When I shut the laptop down, HA remembers the previous state that lnxlink reported for all of my entities, and they don't go unavailable even after several days. For example, the idle time on my laptop has been "3" ever since I shut it down.

I'm trying to create a template sensor for whether or not I'm currently using my laptop, but so far I can't figure out how to make it accurate.

So far, I've come up with:
```
{{ (has_value('sensor.dev_laptop_idle') and 
      (now() | as_local | as_timestamp - states.sensor.dev_laptop_idle.last_changed | as_local | as_timestamp < 120) and 
      (is_state('sensor.dev_laptop_idle', 'OFF') or (states('sensor.dev_laptop_idle') | int) <= 600)) }}
```

However even that causes issues, because after restarting HA, the last_changed timestamp updates to the current time, and it then says I'm using my laptop for at least the next 120 seconds.

Is there any way to have an MQTT entity from lnxlink that goes unavailable when it stops receiving updates so that I can detect when it's no longer receiving data from lnxlink more accurately?

Side note: Is it a bug that when idle time is 0, Home Assistant reports the state as OFF?

**Comment by bkbilly** [comment]
For me when I turn off or restart my PC it automatically becomes unavailable. Could you send me some more info about your system? 
Distribution, version, etc...

Unfortunately home assistant doesn't support on MQTT to check if it doesn't get any events for x time, to set unavailable the entity, but you could create an automation similar to the one you created:
```yaml
alias: lnxlink powered down
description: ""
mode: single
trigger:
  - platform: template
    value_template: >-
      {{ (now() | as_local | as_timestamp -
      states.sensor.desktop_linux_idle.last_changed | as_local | as_timestamp) >
      10 }}
condition: []
action:
  - service: mqtt.publish
    data:
      qos: 0
      retain: true
      topic: lnxlink/desktop-linux/lwt
      payload: "OFF"
```

As for the idle time, I haven't noticed any report for state OFF, but I will keep it in mind.
