### ISSUE TITLE
Brightness slider not working

### ISSUE THREAD

**Issue by rcr083096** [bkbilly/lnxlink#86]
### What type of installation are you running?

Desktop

### Which Linux OS are you using?

Xubuntu 22.04

### Which version of LNXLink has the issue?

2024.1.0

### Describe the problem

Followed setup steps in documentation and screen on/off works, however brightness slider does not work. Debugged to this line in the brightness module:
https://github.com/bkbilly/lnxlink/blob/4c6ced7d2d2b542c643c91163efe97195e3bf468/lnxlink/modules/brightness.py#L59
that was looking for "Brightness" when topic[1] was "brightness" while I was debugging. 

Modified that line to this:
`if str(topic[1]).lower() == "brightness":`
and the brightness slider works now. 

I'm still relatively new to linux in general so I'm not sure if this was an issue on my end setting it up or if it's something specific to Xubuntu or just an actual bug. I was using regular ubuntu desktop 22.04 but the screen on/off feature was not working with Wayland so I switched to X. 

### Additional context

![image](https://github.com/bkbilly/lnxlink/assets/34383411/2adb76f2-e83e-4c17-8dcd-e53337fbcf67)

### Configuration

```yaml
mqtt:
  prefix: lnxlink
  clientId: DESKTOP-Linux
  server: 192.168.1.2
  port: 1887
  auth:
    user: hassio
    pass: removed
    tls: false
  discovery:
    enabled: true
  lwt:
    enabled: true
    qos: 1
    retain: false
    connectMsg: 'ON'
    disconnectMsg: 'OFF'
update_interval: 5
modules:
- display_env
- brightness
- screen_onoff
- media
- fullscreen
- xdg_open
custom_modules: null
exclude: null
settings: null
```

### Logs

```bash
NFO:lnxlink:LNXlink 2024.1.0, Python 3.10.12
INFO:lnxlink:Loaded addons: display_env, brightness, screen_onoff, media, fullscreen, xdg_open
INFO:lnxlink:Connected to MQTT with code 0
INFO:lnxlink:Message received brightness/brightness/: b'0.4'
ERROR:lnxlink:Error with command: xrandr --output brightness --brightness 0.4 --display :0.0 (warning: output brightness not found; ignoring
xrandr: Need crtc to set gamma on.)
```
