### ISSUE TITLE
MQTT Client Certificate Authentication

### ISSUE THREAD

**Issue by Daniel-dev22** [bkbilly/lnxlink#87]
### Describe the solution you'd like

MQTT Client Certificate Authentication can also be referred to as MQTT MTLS.

For this to work additional Mqtt parameters need to be added to the code, client certificate and client key in addition to the certificate authority certificate.

This is how pahomqtt does it. I just got this to work in another project.

https://github.com/jgyates/genmon/issues/1006#issuecomment-1882932513

**Comment by bkbilly** [comment]
When you setup LNXlink, it asks you if you want to use TLS.
You can manually edit your yaml config file so that you can use TLS connection for MQTT.
This looks like so:
```yaml
mqtt:
  prefix: 'lnxlink'
  clientId: 'DESKTOP-Linux'
  server: '192.168.1.1'
  port: 1883
  auth:
    user: 'user'
    pass: 'pass'
    tls: true
  discovery:
    enabled: true
  lwt:
    enabled: true
    qos: 1
    retain: false
    connectMsg: 'ON'
    disconnectMsg: 'OFF'
```

You can see how I use it here: https://github.com/bkbilly/lnxlink/blob/master/lnxlink/__main__.py#L163

This feature was introduced on 2023.9.0 version.
